### ISSUE TITLE
example of implementing config subcommand

### ISSUE THREAD

**Issue by mskymoore** [clueboard/milc#9]
getting this when importing  milc.subcommand.config:

```
Traceback (most recent call last):
  File "/Users/sky/Clients/ucsd/kuali-2-jira-sync/env/bin/ucsd_sol", line 11, in <module>
    load_entry_point('kuali-2-jira-sync', 'console_scripts', 'ucsd_sol')()
  File "/Users/sky/Clients/ucsd/kuali-2-jira-sync/env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/sky/Clients/ucsd/kuali-2-jira-sync/env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2855, in load_entry_point
    return ep.load()
  File "/Users/sky/Clients/ucsd/kuali-2-jira-sync/env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2446, in load
    return self.resolve()
  File "/Users/sky/Clients/ucsd/kuali-2-jira-sync/env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2452, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/sky/Clients/ucsd/kuali-2-jira-sync/src/ucsd_sol/__main__.py", line 2, in <module>
    import milc.subcommand.config
  File "/Users/sky/Clients/ucsd/kuali-2-jira-sync/env/lib/python3.7/site-packages/milc/subcommand/config.py", line 62, in <module>
    @cli.subcommand("Read and write configuration settings.")
  File "/Users/sky/Clients/ucsd/kuali-2-jira-sync/env/lib/python3.7/site-packages/milc/milc.py", line 214, in argument_function
    self.subcommands[subcommand_name].add_argument(*args, **kwargs)
  File "/Users/sky/Clients/ucsd/kuali-2-jira-sync/env/lib/python3.7/site-packages/milc/configuration.py", line 73, in add_argument
    argument_name = self.cli.get_argument_name(*args, **kwargs)
AttributeError: 'MILC' object has no attribute 'get_argument_name'
```

**Comment by mskymoore** [comment]
This is a duplicate.
